// Generated by de.jabc.cinco.meta.plugin.event.generator.template.EventStartupClassTemplate

package info.scce.cinco.product.scchart.mglid.scchart.event

import de.jabc.cinco.meta.runtime.IStartup

class EventStartup implements IStartup {
	
	override startup() {
		subscribe
	}
	
	def static void subscribe() {
		SCChartEvent.instance.subscribe
	}
	
	def static void unsubscribe() {
		SCChartEvent.instance.unsubscribe
	}
	
}
